site_name: My Docs
theme: readthedocs
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js


nav:
 - Get started: index.md
 - Background: introduction.md
